# Generated by Django 6.0.1 on 2026-01-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
